substitutions:
  relayPin_1: GPIO05
  relayPin_2: GPIO04
  relayPin_3: GPIO0
  relayPin_4: GPIO02
  switchPin_1: GPIO03
  switchPin_2: GPIO14
  switchPin_3: GPIO12
  switchPin_4: GPIO13
  
esphome:
  name: bedroom2
  platform: ESP8266
  board: d1_mini
  name_add_mac_suffix: true
  project:
    name: "MDtronix.4ch_Smart Switch"
    version: "1.0"
    
wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom2 Fallback Hotspot"
    password: "mdtronics"

captive_portal:
logger:
api:
ota:
web_server:
  port: 80

output:
  - platform: gpio
    pin: $relayPin_1
    id: relay_1
  - platform: gpio
    pin: $relayPin_2
    id: relay_2
  - platform: gpio
    pin: $relayPin_3
    id: relay_3
  - platform: gpio
    pin: $relayPin_4
    id: relay_4
   
# light:
#   - platform: binary
#     output: relay_1
#     name: $deviceName Tube
#     id: light_1
#   - platform: binary
#     output: relay_2
#     name: $deviceName Bulb
#     id: light_2
#   - platform: binary
#     output: relay_3
#     name: Backyard Bulb
#     id: light_3

# fan:
#   - platform: binary
#     output: relay_4
#     name: $deviceName Fan
#     id: fan_1
    
# binary_sensor:
#   - platform: status
#     name: $deviceName Status
    
#   - platform: gpio
#     id: switch_1
#     pin:
#       number: $switchPin_1
#       mode: INPUT_PULLUP
#       inverted: true
#     on_state:
#       - light.toggle: light_1
      
#   - platform: gpio
#     id: Switch_2
#     pin:
#       number: $switchPin_2
#       mode: INPUT_PULLUP
#       inverted: true
#     on_state:
#       - light.toggle: light_2
    
#   - platform: gpio
#     id: Switch_3
#     pin:
#       number: $switchPin_3
#       mode: INPUT_PULLUP
#       inverted: true
#     on_state:
#       - light.toggle: light_3
      
#   - platform: gpio
#     id: Switch_4
#     pin:
#       number: $switchPin_4
#       mode: INPUT_PULLUP
#       inverted: true
#     on_state:
#       - fan.toggle: fan_1
